#!/usr/bin/env bash
# send a file to the server

if (( $# < 3 )); then
    echo "Usage: 0-send a file to the server transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi