#!/usr/bin/env bash
#  Install nginx on server
find="^\tlocation / {"
replace301="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "s@$find@$replace301@" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
