#!/usr/bin/env bash
# Task 0 World Wide Web
func () {
	if [ $# -eq "2" ]; then	
		dig "$2.$1"  | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
	elif [ $# -eq 1 ]; then
		for sub in 'www' 'lb-01' 'web-01' 'web-02'; do
			var=$sub.$1
	    	dig "$var" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var=$sub
		done
	fi
}

func "$@"